statsApiLinkPoE2=https://www.pathofexile.com/api/trade2/data/stats
statsApiLink=https://www.pathofexile.com/api/trade/data/stats
itemsApiLinkPoE2=https://www.pathofexile.com/api/trade2/data/items
itemsApiLink=https://www.pathofexile.com/api/trade/data/items
tradeApiSearchUrl=https://www.pathofexile.com/api/trade/search/
tradeApiSearchUrlPoE2=https://www.pathofexile.com/api/trade2/search/
tradeApiRequestDelayMs=10000
tradeWebSearchUrl=https://www.pathofexile.com/trade/search/
tradeWebSearchUrlPoE2=https://www.pathofexile.com/trade2/search/poe2/
